---
title: Lección 1 - Introducción a rmarkdown
output: html_document
---


## Presentación

La presentación de la primera lección se encuentran aqui: https://docs.google.com/presentation/d/1nUJGAnr7iudZSUNDJBq-ddpzRbe6zaZIQzFr8SXrHH8/edit?usp=sharing 


## Rmarkdown

Si en tu trabajo tenes que presentar informes o resultados de tu análisis de datos, tal vez te hayas encontrando usando más de un software, por ejemplo Word para el texto y Excel para los gráficos.  Tal vez has tenido que guardar más de vez gráficos y tablas y hayas copiado resultados de un archivo al otro hasta que el informe quedó como querías. 

Rmarkdown tiene como filosofía un solo formato, varias salidas. Esto significa que escribiendo en un solo formato podemos tener varias salidas como Words, PDF, HTMLs, entre varios otros.

Además, un archivo de R Markdown (generalmente con la extensión _.Rmd_), a diferencia de un script _.R_, es un archivo de texto plano que combina código de R que genera resultados (gráficos, tablas, etc…) y el texto que lo describe. Al poder intercalar cálculos y gráficos con su análisis o explicación, se unifica el flujo de trabajo y deja de ser necesario guardar figuras o tablas para luego insertarlas en un documento de texto. Esto es muy importante si buscamos que nuestro trabajo sea reproducible, pero además ahorra tiempo.

